apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-debug-deployment
  labels:
    app: goapp-debug
    key: {{ .Values.key }}
spec:
  selector:
    matchLabels:
      app: goapp-debug
  replicas: 1
  template:
    metadata:
      labels:
        app: goapp-debug
    spec:
      containers:
        - name: goapp-debug
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
