name: Push Chart to vCR

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Log in to the GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: login to acr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/${{ github.repository_owner }}/vks/annd2 --username ${{ github.repository_owner }} --password-stdin

      - name: save helm chart to local registry
        run: |
          rm -rf ${{ github.workspace }}/charts/goapp-debug/*.tgz
          helm package ${{ github.workspace }}/charts/goapp-debug/
          cd ${{ github.workspace }}/charts/goapp-debug && helm push *.tgz oci://ghcr.io/${{ github.repository_owner }}/vks

